function waveform = importLecroyWaveform(filename, dataLines)
%IMPORTFILE Import data from a text file
%  WAVEFORM = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  WAVEFORM = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  waveform = importfile("D:\Trevor\My Documents\MED lab\Cochlear R01\Impedance Sensing\Experiments\Calibration testing\2019-10-23\F1_z_400ms00000.csv", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Oct-2019 10:25:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["t", "v", "Var3"];
opts.SelectedVariableNames = ["t", "v"];
opts.VariableTypes = ["double", "double", "string"];
opts = setvaropts(opts, 3, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 3, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Setup rules for import
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";

% Import the data
waveform = readtable(filename, opts);

end