function [fitresult, gof] = ZsensingNonlinearFit(A47, Z47, W, A6, Z6)
%CREATEFIT(A47,Z47,W,A6,Z6)
%  Create a fit.
%
%  Data for 'Trials4&7' fit:
%      X Input : A47
%      Y Output: Z47
%      Weights : W
%      Validation X: A6
%      Validation Y: Z6
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Feb-2020 00:39:18


%% Fit: 'Trials4&7'.
[xData, yData, weights] = prepareCurveData( A47, Z47, W );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Robust = 'Bisquare';
opts.StartPoint = [267.658914371033 -0.883654710764583];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Compare against validation data.
[xValidation, yValidation] = prepareCurveData( A6, Z6 );
residual = yValidation - fitresult( xValidation );
nNaN = nnz( isnan( residual ) );
residual(isnan( residual )) = [];
sse = norm( residual )^2;
rmse = sqrt( sse/length( residual ) );
fprintf( 'Goodness-of-validation for ''%s'' fit:\n', 'Trials4&7' );
fprintf( '    SSE : %f\n', sse );
fprintf( '    RMSE : %f\n', rmse );
fprintf( '    %i points outside domain of data.\n', nNaN );

% Create a figure for the plots.
figure( 'Name', 'Trials4&7' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
% Add validation data to plot.
hold on
h(end+1) = plot( xValidation, yValidation, 'bo', 'MarkerFaceColor', 'w' );
hold off
legend( h, 'Z47 vs. A47 with W', 'Trials4&7', 'Z6 vs. A6', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'A47', 'Interpreter', 'none' );
ylabel( 'Z47', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
% Add validation data to plot.
hold on
h(end+1) = plot( xValidation, yValidation - fitresult( xValidation ), 'bo', 'MarkerFaceColor', 'w' );
hold off
legend( h, 'Trials4&7 - residuals', 'Zero Line', 'Trials4&7 - validation residuals', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'A47', 'Interpreter', 'none' );
ylabel( 'Z47', 'Interpreter', 'none' );
grid on


